spring.application.name=restapi-shopping

# DB config
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/restapi_shopping_db?serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=1234

# JPA
spring.jpa.show-sql=true
spring.jpa.format-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# log level
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.csrf=TRACE

# Swagger
# 1. ??? ??? ??? ?? ??
springdoc.packages-to-scan=dev.shopping.controller

# 2. ??? ??? API ?? ?? ??
springdoc.paths-to-match=/api/products

# 3. Swagger UI ?? ?? ??
springdoc.swagger-ui.path=/swagger-ui.html

# 4. ?? ? ??? ?? ?? (?? ??? ??)
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=method

# Swagger ?? ? '?? ???' ??? ???? ???
springdoc.swagger-ui.display-query-params=true
springdoc.swagger-ui.urls-primary-name=?? ???